image: python:3.11.2
.set_environment: &set_environment |
  export POETRY_HOME="/opt/poetry"
  export VENV_PATH="/opt/collab/.venv"
  export PATH="${POETRY_HOME}/bin:${VENV_PATH}/bin:${PATH}"

.install_poetry: &install_poetry |
  pip install --upgrade "pip>=21.1"
  pip install poetry==1.4.2
  poetry install --no-interaction --no-ansi

pipelines:
  default:
    - step:
        name: Run tests
        script:
          - *set_environment
          - *install_poetry
          - poetry run make test

    - step:
        name: Formatting with isort and black
        script:
          - *set_environment
          - *install_poetry
          - poetry run make format

    - step:
        name: Check code formatting
        script:
          - *set_environment
          - *install_poetry
          - poetry run make check-format